---
version: '3.3'

services:
  bookstack-db:
    image: mysql:5.7
    container_name: bookstack-db
    restart: always
    volumes:
      - /var/docker/bookstack/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= # Setze hier ein starkes Passwort
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD= # Ein anderes Passwort

  bookstack-app:
    image: solidnerd/bookstack
    container_name: bookstack-app
    restart: always
    volumes:
      - /var/docker/bookstack/app/uploads:/var/www/bookstack/public/uploads
      - /var/docker/bookstack/app/storage-uploads:/var/www/bookstack/public/storage
    environment:
      - DB_HOST=bookstack-db:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD= # Hier das Passwort von MYSQL_PASSWORD aus dem Datenbankcontainer setzen
    labels:
      - "traefik.backend=bookstack"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:bookstack.example.com" # URL entsprechend anpassen!
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge