---
version: '3'
services:
 ouroboros:
    image: pyouroboros/ouroboros:latest
    container_name: ouroboros
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - INTERVAL=43200 # Überprüft alle 12 Stunden - Angabe in Sekunden
      - LOG_LEVEL=error
      - SELF_UPDATE=true
#      - IGNORE=mysql # Ignoriert angegebene Container (Containernamen angeben!)
      - CLEANUP=true # Löscht die alten Container nach erfolgreichem Update
      - TZ=Europe/Berlin
